import { assetUrl } from './assets.js';

/**
 * Fruit definitions inspired by Blox Fruits / One Piece.
 * Each fruit grants 3-4 combat skills that replace the default hotbar.
 *
 * Skill properties:
 *   id          – unique key
 *   name        – display name (Traditional Chinese)
 *   icon        – hotbar icon URL
 *   kind        – 'attack' | 'block'
 *   range       – effective hit range (units)
 *   swingMs     – animation duration
 *   cooldownMs  – cooldown after use
 *   knockback   – knockback strength on hit
 *   damage      – base damage multiplier (applied on top of player.baseAttack)
 *   particleColor – hit particle colour
 *   particleCount – number of particles on hit
 */

export const FRUITS = [
  {
    id: 'rubber',
    name: '橡膠果實',
    desc: '身體如橡膠般伸縮自如，擅長遠距拳擊',
    color: '#e04040',
    skills: [
      {
        id: 'rubber_pistol',
        name: '橡膠槍',
        icon: assetUrl('assets/kenney/skills/rubber_punch.png'),
        kind: 'attack',
        range: 6.2,
        swingMs: 260,
        cooldownMs: 360,
        knockback: 7.4,
        damage: 1,
        particleColor: 'white',
        particleCount: 14,
        weaponType: 'punch',
      },
      {
        id: 'rubber_shotgun',
        name: '橡膠散彈槍',
        icon: assetUrl('assets/kenney/skills/rubber_punch.png'),
        kind: 'attack',
        range: 3.0,
        swingMs: 200,
        cooldownMs: 280,
        knockback: 3.2,
        damage: 2,
        particleColor: 'yellow',
        particleCount: 20,
        weaponType: 'punch',
      },
      {
        id: 'rubber_bazooka',
        name: '橡膠火箭砲',
        icon: assetUrl('assets/kenney/skills/rubber_punch.png'),
        kind: 'attack',
        range: 5.0,
        swingMs: 340,
        cooldownMs: 600,
        knockback: 12.0,
        damage: 3,
        particleColor: 'orange',
        particleCount: 18,
        weaponType: 'punch',
      },
      {
        id: 'rubber_bell',
        name: '橡膠鐘',
        icon: assetUrl('assets/kenney/skills/rubber_punch.png'),
        kind: 'attack',
        range: 2.5,
        swingMs: 300,
        cooldownMs: 500,
        knockback: 9.0,
        damage: 4,
        particleColor: 'gold',
        particleCount: 22,
        weaponType: 'punch',
      },
    ],
  },
  {
    id: 'flame',
    name: '火焰果實',
    desc: '身體化為烈焰，操縱火焰攻擊敵人',
    color: '#ff6b35',
    skills: [
      {
        id: 'fire_fist',
        name: '火拳',
        icon: assetUrl('assets/kenney/skills/rubber_punch.png'),
        kind: 'attack',
        range: 4.5,
        swingMs: 240,
        cooldownMs: 340,
        knockback: 6.0,
        damage: 2,
        particleColor: 'orange',
        particleCount: 16,
        weaponType: 'punch',
      },
      {
        id: 'fire_pillar',
        name: '火柱',
        icon: assetUrl('assets/kenney/skills/rubber_punch.png'),
        kind: 'attack',
        range: 3.5,
        swingMs: 300,
        cooldownMs: 500,
        knockback: 5.0,
        damage: 3,
        particleColor: 'red',
        particleCount: 24,
        weaponType: 'punch',
      },
      {
        id: 'flame_emperor',
        name: '炎帝',
        icon: assetUrl('assets/kenney/skills/rubber_punch.png'),
        kind: 'attack',
        range: 7.0,
        swingMs: 400,
        cooldownMs: 800,
        knockback: 10.0,
        damage: 5,
        particleColor: 'orange',
        particleCount: 28,
        weaponType: 'punch',
      },
    ],
  },
  {
    id: 'ice',
    name: '冰凍果實',
    desc: '將一切凍結的冰之力量',
    color: '#6ec6ff',
    skills: [
      {
        id: 'ice_spear',
        name: '冰槍',
        icon: assetUrl('assets/kenney/items/sword_diamond.png'),
        kind: 'attack',
        range: 6.5,
        swingMs: 280,
        cooldownMs: 400,
        knockback: 5.5,
        damage: 2,
        particleColor: 'cyan',
        particleCount: 14,
        weaponType: 'sword',
      },
      {
        id: 'ice_age',
        name: '冰河時代',
        icon: assetUrl('assets/kenney/skills/rubber_punch.png'),
        kind: 'attack',
        range: 4.0,
        swingMs: 360,
        cooldownMs: 700,
        knockback: 4.0,
        damage: 4,
        particleColor: 'white',
        particleCount: 30,
        weaponType: 'punch',
      },
      {
        id: 'ice_saber',
        name: '冰劍',
        icon: assetUrl('assets/kenney/items/sword_diamond.png'),
        kind: 'attack',
        range: 3.0,
        swingMs: 180,
        cooldownMs: 250,
        knockback: 3.8,
        damage: 1,
        particleColor: 'cyan',
        particleCount: 10,
        weaponType: 'sword',
      },
    ],
  },
  {
    id: 'lightning',
    name: '閃電果實',
    desc: '化身雷電，以電流摧毀一切',
    color: '#ffe060',
    skills: [
      {
        id: 'thunder_bolt',
        name: '萬雷',
        icon: assetUrl('assets/kenney/skills/rubber_punch.png'),
        kind: 'attack',
        range: 7.0,
        swingMs: 200,
        cooldownMs: 350,
        knockback: 6.0,
        damage: 2,
        particleColor: 'yellow',
        particleCount: 18,
        weaponType: 'punch',
      },
      {
        id: 'lightning_rush',
        name: '閃電衝擊',
        icon: assetUrl('assets/kenney/skills/rubber_punch.png'),
        kind: 'attack',
        range: 3.0,
        swingMs: 140,
        cooldownMs: 280,
        knockback: 8.0,
        damage: 2,
        particleColor: 'white',
        particleCount: 16,
        weaponType: 'punch',
      },
      {
        id: 'thunder_dragon',
        name: '雷龍',
        icon: assetUrl('assets/kenney/skills/rubber_punch.png'),
        kind: 'attack',
        range: 8.0,
        swingMs: 380,
        cooldownMs: 750,
        knockback: 11.0,
        damage: 5,
        particleColor: 'yellow',
        particleCount: 26,
        weaponType: 'punch',
      },
    ],
  },
  {
    id: 'dark',
    name: '暗暗果實',
    desc: '操縱黑暗與重力，吞噬一切',
    color: '#6a3d99',
    skills: [
      {
        id: 'dark_pull',
        name: '闇水',
        icon: assetUrl('assets/kenney/skills/rubber_punch.png'),
        kind: 'attack',
        range: 7.0,
        swingMs: 300,
        cooldownMs: 450,
        knockback: -6.0,
        damage: 1,
        particleColor: 'purple',
        particleCount: 14,
        weaponType: 'punch',
      },
      {
        id: 'black_hole',
        name: '黑洞',
        icon: assetUrl('assets/kenney/skills/rubber_punch.png'),
        kind: 'attack',
        range: 5.0,
        swingMs: 360,
        cooldownMs: 650,
        knockback: 3.0,
        damage: 4,
        particleColor: 'purple',
        particleCount: 24,
        weaponType: 'punch',
      },
      {
        id: 'liberation',
        name: '解放',
        icon: assetUrl('assets/kenney/skills/rubber_punch.png'),
        kind: 'attack',
        range: 4.0,
        swingMs: 280,
        cooldownMs: 500,
        knockback: 9.0,
        damage: 3,
        particleColor: 'black',
        particleCount: 20,
        weaponType: 'punch',
      },
    ],
  },
  {
    id: 'light',
    name: '光光果實',
    desc: '以光速移動與攻擊，無人能擋',
    color: '#fff4a0',
    skills: [
      {
        id: 'light_beam',
        name: '光束',
        icon: assetUrl('assets/kenney/skills/rubber_punch.png'),
        kind: 'attack',
        range: 8.0,
        swingMs: 160,
        cooldownMs: 300,
        knockback: 5.0,
        damage: 2,
        particleColor: 'yellow',
        particleCount: 12,
        weaponType: 'punch',
      },
      {
        id: 'flash_step',
        name: '閃光',
        icon: assetUrl('assets/kenney/skills/rubber_punch.png'),
        kind: 'attack',
        range: 3.5,
        swingMs: 120,
        cooldownMs: 250,
        knockback: 4.0,
        damage: 1,
        particleColor: 'white',
        particleCount: 16,
        weaponType: 'punch',
      },
      {
        id: 'light_sword',
        name: '天叢雲劍',
        icon: assetUrl('assets/kenney/items/sword_diamond.png'),
        kind: 'attack',
        range: 3.5,
        swingMs: 160,
        cooldownMs: 220,
        knockback: 4.5,
        damage: 2,
        particleColor: 'yellow',
        particleCount: 14,
        weaponType: 'sword',
      },
      {
        id: 'laser_rain',
        name: '八尺瓊勾玉',
        icon: assetUrl('assets/kenney/skills/rubber_punch.png'),
        kind: 'attack',
        range: 6.0,
        swingMs: 400,
        cooldownMs: 900,
        knockback: 7.0,
        damage: 5,
        particleColor: 'yellow',
        particleCount: 30,
        weaponType: 'punch',
      },
    ],
  },
  {
    id: 'quake',
    name: '震震果實',
    desc: '引發地震的毀滅力量，撼動大地',
    color: '#c0a030',
    skills: [
      {
        id: 'quake_punch',
        name: '震動拳',
        icon: assetUrl('assets/kenney/skills/rubber_punch.png'),
        kind: 'attack',
        range: 4.0,
        swingMs: 280,
        cooldownMs: 400,
        knockback: 10.0,
        damage: 3,
        particleColor: 'white',
        particleCount: 20,
        weaponType: 'punch',
      },
      {
        id: 'seismic_wave',
        name: '海震',
        icon: assetUrl('assets/kenney/skills/rubber_punch.png'),
        kind: 'attack',
        range: 6.0,
        swingMs: 340,
        cooldownMs: 600,
        knockback: 8.0,
        damage: 3,
        particleColor: 'yellow',
        particleCount: 22,
        weaponType: 'punch',
      },
      {
        id: 'space_shatter',
        name: '空間粉碎',
        icon: assetUrl('assets/kenney/skills/rubber_punch.png'),
        kind: 'attack',
        range: 5.0,
        swingMs: 400,
        cooldownMs: 800,
        knockback: 14.0,
        damage: 5,
        particleColor: 'white',
        particleCount: 28,
        weaponType: 'punch',
      },
    ],
  },
  {
    id: 'magma',
    name: '岩漿果實',
    desc: '化身滾燙岩漿，燃燒一切',
    color: '#cc3300',
    skills: [
      {
        id: 'magma_fist',
        name: '大噴火',
        icon: assetUrl('assets/kenney/skills/rubber_punch.png'),
        kind: 'attack',
        range: 5.0,
        swingMs: 300,
        cooldownMs: 450,
        knockback: 7.0,
        damage: 3,
        particleColor: 'red',
        particleCount: 18,
        weaponType: 'punch',
      },
      {
        id: 'meteor_volcano',
        name: '流星火山',
        icon: assetUrl('assets/kenney/skills/rubber_punch.png'),
        kind: 'attack',
        range: 7.0,
        swingMs: 420,
        cooldownMs: 850,
        knockback: 6.0,
        damage: 5,
        particleColor: 'orange',
        particleCount: 30,
        weaponType: 'punch',
      },
      {
        id: 'magma_hound',
        name: '犬噛紅蓮',
        icon: assetUrl('assets/kenney/skills/rubber_punch.png'),
        kind: 'attack',
        range: 4.5,
        swingMs: 260,
        cooldownMs: 400,
        knockback: 8.5,
        damage: 2,
        particleColor: 'red',
        particleCount: 16,
        weaponType: 'punch',
      },
    ],
  },
  {
    id: 'sand',
    name: '沙沙果實',
    desc: '化身為沙，侵蝕與風暴並用',
    color: '#d4a843',
    skills: [
      {
        id: 'desert_sword',
        name: '砂漠寶刀',
        icon: assetUrl('assets/kenney/items/sword_diamond.png'),
        kind: 'attack',
        range: 5.5,
        swingMs: 240,
        cooldownMs: 350,
        knockback: 5.5,
        damage: 2,
        particleColor: 'yellow',
        particleCount: 14,
        weaponType: 'sword',
      },
      {
        id: 'sand_trap',
        name: '流砂',
        icon: assetUrl('assets/kenney/skills/rubber_punch.png'),
        kind: 'attack',
        range: 4.0,
        swingMs: 300,
        cooldownMs: 500,
        knockback: 2.0,
        damage: 3,
        particleColor: 'yellow',
        particleCount: 20,
        weaponType: 'punch',
      },
      {
        id: 'sandstorm',
        name: '砂嵐',
        icon: assetUrl('assets/kenney/skills/rubber_punch.png'),
        kind: 'attack',
        range: 6.0,
        swingMs: 380,
        cooldownMs: 700,
        knockback: 7.0,
        damage: 4,
        particleColor: 'orange',
        particleCount: 26,
        weaponType: 'punch',
      },
    ],
  },
  {
    id: 'bomb',
    name: '爆爆果實',
    desc: '將一切化為爆炸，破壞力驚人',
    color: '#ff4444',
    skills: [
      {
        id: 'bomb_punch',
        name: '爆拳',
        icon: assetUrl('assets/kenney/skills/rubber_punch.png'),
        kind: 'attack',
        range: 3.5,
        swingMs: 220,
        cooldownMs: 320,
        knockback: 8.0,
        damage: 2,
        particleColor: 'orange',
        particleCount: 18,
        weaponType: 'punch',
      },
      {
        id: 'land_mine',
        name: '地雷',
        icon: assetUrl('assets/kenney/skills/rubber_punch.png'),
        kind: 'attack',
        range: 3.0,
        swingMs: 260,
        cooldownMs: 450,
        knockback: 10.0,
        damage: 3,
        particleColor: 'red',
        particleCount: 22,
        weaponType: 'punch',
      },
      {
        id: 'big_explosion',
        name: '大爆炸',
        icon: assetUrl('assets/kenney/skills/rubber_punch.png'),
        kind: 'attack',
        range: 5.0,
        swingMs: 400,
        cooldownMs: 900,
        knockback: 14.0,
        damage: 6,
        particleColor: 'red',
        particleCount: 32,
        weaponType: 'punch',
      },
    ],
  },
];
