import { assetUrl } from './assets.js';

/**
 * Fruit definitions inspired by Blox Fruits / One Piece.
 * Each fruit grants 3-4 combat skills that replace the default hotbar.
 *
 * Skill properties:
 *   id          – unique key
 *   name        – display name (Traditional Chinese)
 *   icon        – hotbar icon URL
 *   kind        – 'attack' | 'block'
 *   range       – effective hit range (units)
 *   swingMs     – animation duration
 *   cooldownMs  – cooldown after use
 *   knockback   – knockback strength on hit
 *   damage      – base damage multiplier (applied on top of player.baseAttack)
 *   particleColor – hit particle colour
 *   particleCount – number of particles on hit
 *   weaponType  – animation type: sword, punch, cast, slam, uppercut, clap
 */

export const FRUITS = [
  {
    id: 'rubber',
    name: '橡膠果實',
    desc: '身體如橡膠般伸縮自如，擅長遠距拳擊',
    color: '#e04040',
    animStyle: 'stretch',
    skills: [
      {
        id: 'rubber_pistol',
        name: '橡膠槍',
        desc: '伸長手臂直拳攻擊，範圍6.2，攻擊力×1，CD 0.36秒。遠距單體打擊',
        icon: assetUrl('assets/kenney/skills/rubber_punch.png'),
        kind: 'attack',
        range: 6.2,
        swingMs: 260,
        cooldownMs: 360,
        knockback: 7.4,
        damage: 1,
        particleColor: 'white',
        particleCount: 14,
        weaponType: 'punch',
      },
      {
        id: 'rubber_shotgun',
        name: '橡膠散彈槍',
        desc: '近距離連續重拳，範圍3.0，攻擊力×2，CD 0.28秒。快速近戰連擊',
        icon: assetUrl('assets/kenney/skills/rubber_punch.png'),
        kind: 'attack',
        range: 3.0,
        swingMs: 200,
        cooldownMs: 280,
        knockback: 3.2,
        damage: 2,
        particleColor: 'yellow',
        particleCount: 20,
        weaponType: 'uppercut',
      },
      {
        id: 'rubber_bazooka',
        name: '橡膠火箭砲',
        desc: '雙手合掌發射強力衝擊，範圍5.0，攻擊力×3，CD 0.6秒。強力擊退效果',
        icon: assetUrl('assets/kenney/skills/rubber_punch.png'),
        kind: 'attack',
        range: 5.0,
        swingMs: 340,
        cooldownMs: 600,
        knockback: 12.0,
        damage: 3,
        particleColor: 'orange',
        particleCount: 18,
        weaponType: 'clap',
      },
      {
        id: 'rubber_bell',
        name: '橡膠鐘',
        desc: '頭部猛力撞擊，範圍2.5，攻擊力×4，CD 0.5秒。近距離高傷害擊退',
        icon: assetUrl('assets/kenney/skills/rubber_punch.png'),
        kind: 'attack',
        range: 2.5,
        swingMs: 300,
        cooldownMs: 500,
        knockback: 9.0,
        damage: 4,
        particleColor: 'gold',
        particleCount: 22,
        weaponType: 'slam',
      },
    ],
  },
  {
    id: 'flame',
    name: '火焰果實',
    desc: '身體化為烈焰，操縱火焰攻擊敵人',
    color: '#ff6b35',
    animStyle: 'fire',
    skills: [
      {
        id: 'fire_fist',
        name: '火拳',
        desc: '拳頭化為烈焰揮出，範圍4.5，攻擊力×2，CD 0.34秒。中距火焰打擊',
        icon: assetUrl('assets/kenney/skills/rubber_punch.png'),
        kind: 'attack',
        range: 4.5,
        swingMs: 340,
        cooldownMs: 340,
        knockback: 6.0,
        damage: 2,
        particleColor: 'orange',
        particleCount: 16,
        weaponType: 'fire_fist',
      },
      {
        id: 'fire_pillar',
        name: '火柱',
        desc: '召喚火焰柱噴發，範圍3.5，攻擊力×3，CD 0.5秒。近距範圍燃燒',
        icon: assetUrl('assets/kenney/skills/rubber_punch.png'),
        kind: 'attack',
        range: 3.5,
        swingMs: 300,
        cooldownMs: 500,
        knockback: 5.0,
        damage: 3,
        particleColor: 'red',
        particleCount: 24,
        weaponType: 'cast',
      },
      {
        id: 'flame_emperor',
        name: '炎帝',
        desc: '釋放巨大火球轟炸，範圍18，攻擊力×5，CD 5秒。遠距範圍爆炸高傷害',
        icon: assetUrl('assets/kenney/skills/rubber_punch.png'),
        kind: 'attack',
        range: 18,
        swingMs: 400,
        cooldownMs: 5000,
        knockback: 10.0,
        damage: 5,
        particleColor: 'orange',
        particleCount: 28,
        weaponType: 'flame_emperor',
        aoeRadius: 5,
      },
    ],
  },
  {
    id: 'ice',
    name: '冰凍果實',
    desc: '將一切凍結的冰之力量',
    color: '#6ec6ff',
    animStyle: 'ice',
    skills: [
      {
        id: 'ice_spear',
        name: '冰槍',
        desc: '凝結冰矛刺擊敵人，範圍6.5，攻擊力×2，CD 0.4秒。遠距劍系冰凍攻擊',
        icon: assetUrl('assets/kenney/items/sword_diamond.png'),
        kind: 'attack',
        range: 6.5,
        swingMs: 280,
        cooldownMs: 400,
        knockback: 5.5,
        damage: 2,
        particleColor: 'cyan',
        particleCount: 14,
        weaponType: 'sword',
      },
      {
        id: 'ice_age',
        name: '冰河時代',
        desc: '釋放極寒凍氣覆蓋範圍，範圍4.0，攻擊力×4，CD 0.7秒。範圍凍結高傷害',
        icon: assetUrl('assets/kenney/skills/rubber_punch.png'),
        kind: 'attack',
        range: 4.0,
        swingMs: 360,
        cooldownMs: 700,
        knockback: 4.0,
        damage: 4,
        particleColor: 'white',
        particleCount: 30,
        weaponType: 'cast',
      },
      {
        id: 'ice_saber',
        name: '冰劍',
        desc: '凝結冰刃快速斬擊，範圍3.0，攻擊力×1，CD 0.25秒。極速近戰連斬',
        icon: assetUrl('assets/kenney/items/sword_diamond.png'),
        kind: 'attack',
        range: 3.0,
        swingMs: 180,
        cooldownMs: 250,
        knockback: 3.8,
        damage: 1,
        particleColor: 'cyan',
        particleCount: 10,
        weaponType: 'sword',
      },
    ],
  },
  {
    id: 'lightning',
    name: '閃電果實',
    desc: '化身雷電，以電流摧毀一切',
    color: '#ffe060',
    animStyle: 'lightning',
    skills: [
      {
        id: 'thunder_bolt',
        name: '萬雷',
        desc: '召喚雷電劈擊敵人，範圍7.0，攻擊力×2，CD 0.35秒。遠距快速雷擊',
        icon: assetUrl('assets/kenney/skills/rubber_punch.png'),
        kind: 'attack',
        range: 7.0,
        swingMs: 200,
        cooldownMs: 350,
        knockback: 6.0,
        damage: 2,
        particleColor: 'yellow',
        particleCount: 18,
        weaponType: 'cast',
      },
      {
        id: 'lightning_rush',
        name: '閃電衝擊',
        desc: '化為雷電衝撞敵人，範圍3.0，攻擊力×2，CD 0.28秒。近距強力擊退',
        icon: assetUrl('assets/kenney/skills/rubber_punch.png'),
        kind: 'attack',
        range: 3.0,
        swingMs: 140,
        cooldownMs: 280,
        knockback: 8.0,
        damage: 2,
        particleColor: 'white',
        particleCount: 16,
        weaponType: 'uppercut',
      },
      {
        id: 'thunder_dragon',
        name: '雷龍',
        desc: '召喚雷龍形態轟擊，範圍8.0，攻擊力×5，CD 0.75秒。超遠距高傷害擊退',
        icon: assetUrl('assets/kenney/skills/rubber_punch.png'),
        kind: 'attack',
        range: 8.0,
        swingMs: 380,
        cooldownMs: 750,
        knockback: 11.0,
        damage: 5,
        particleColor: 'yellow',
        particleCount: 26,
        weaponType: 'clap',
      },
    ],
  },
  {
    id: 'dark',
    name: '暗暗果實',
    desc: '操縱黑暗與重力，吞噬一切',
    color: '#6a3d99',
    animStyle: 'dark',
    skills: [
      {
        id: 'dark_pull',
        name: '闇水',
        desc: '釋放黑暗引力吸引敵人，範圍7.0，攻擊力×1，CD 0.45秒。遠距吸引效果',
        icon: assetUrl('assets/kenney/skills/rubber_punch.png'),
        kind: 'attack',
        range: 7.0,
        swingMs: 300,
        cooldownMs: 450,
        knockback: -6.0,
        damage: 1,
        particleColor: 'purple',
        particleCount: 14,
        weaponType: 'cast',
      },
      {
        id: 'black_hole',
        name: '黑洞',
        desc: '產生黑洞吞噬敵人，範圍5.0，攻擊力×4，CD 0.65秒。高傷害重力壓制',
        icon: assetUrl('assets/kenney/skills/rubber_punch.png'),
        kind: 'attack',
        range: 5.0,
        swingMs: 360,
        cooldownMs: 650,
        knockback: 3.0,
        damage: 4,
        particleColor: 'purple',
        particleCount: 24,
        weaponType: 'clap',
      },
      {
        id: 'liberation',
        name: '解放',
        desc: '釋放吸收的黑暗能量，範圍4.0，攻擊力×3，CD 0.5秒。中距強力擊退',
        icon: assetUrl('assets/kenney/skills/rubber_punch.png'),
        kind: 'attack',
        range: 4.0,
        swingMs: 280,
        cooldownMs: 500,
        knockback: 9.0,
        damage: 3,
        particleColor: 'black',
        particleCount: 20,
        weaponType: 'slam',
      },
    ],
  },
  {
    id: 'light',
    name: '光光果實',
    desc: '以光速移動與攻擊，無人能擋',
    color: '#fff4a0',
    animStyle: 'light',
    skills: [
      {
        id: 'light_beam',
        name: '光束',
        desc: '發射高速光束貫穿敵人，範圍8.0，攻擊力×2，CD 0.3秒。超遠距快速射擊',
        icon: assetUrl('assets/kenney/skills/rubber_punch.png'),
        kind: 'attack',
        range: 8.0,
        swingMs: 160,
        cooldownMs: 300,
        knockback: 5.0,
        damage: 2,
        particleColor: 'yellow',
        particleCount: 12,
        weaponType: 'cast',
      },
      {
        id: 'flash_step',
        name: '閃光',
        desc: '以光速瞬移攻擊，範圍3.5，攻擊力×1，CD 0.25秒。極速近戰連擊',
        icon: assetUrl('assets/kenney/skills/rubber_punch.png'),
        kind: 'attack',
        range: 3.5,
        swingMs: 120,
        cooldownMs: 250,
        knockback: 4.0,
        damage: 1,
        particleColor: 'white',
        particleCount: 16,
        weaponType: 'uppercut',
      },
      {
        id: 'light_sword',
        name: '天叢雲劍',
        desc: '凝聚光之劍刃斬擊，範圍3.5，攻擊力×2，CD 0.22秒。極速劍系連斬',
        icon: assetUrl('assets/kenney/items/sword_diamond.png'),
        kind: 'attack',
        range: 3.5,
        swingMs: 160,
        cooldownMs: 220,
        knockback: 4.5,
        damage: 2,
        particleColor: 'yellow',
        particleCount: 14,
        weaponType: 'sword',
      },
      {
        id: 'laser_rain',
        name: '八尺瓊勾玉',
        desc: '從空中降下大量光彈，範圍6.0，攻擊力×5，CD 0.9秒。遠距範圍高傷害',
        icon: assetUrl('assets/kenney/skills/rubber_punch.png'),
        kind: 'attack',
        range: 6.0,
        swingMs: 400,
        cooldownMs: 900,
        knockback: 7.0,
        damage: 5,
        particleColor: 'yellow',
        particleCount: 30,
        weaponType: 'clap',
      },
    ],
  },
  {
    id: 'quake',
    name: '震震果實',
    desc: '引發地震的毀滅力量，撼動大地',
    color: '#c0a030',
    animStyle: 'quake',
    skills: [
      {
        id: 'quake_punch',
        name: '震動拳',
        desc: '以震動力衝擊敵人，範圍4.0，攻擊力×3，CD 0.4秒。中距強力擊退',
        icon: assetUrl('assets/kenney/skills/rubber_punch.png'),
        kind: 'attack',
        range: 4.0,
        swingMs: 280,
        cooldownMs: 400,
        knockback: 10.0,
        damage: 3,
        particleColor: 'white',
        particleCount: 20,
        weaponType: 'slam',
      },
      {
        id: 'seismic_wave',
        name: '海震',
        desc: '製造地震波向前擴散，範圍6.0，攻擊力×3，CD 0.6秒。遠距範圍擊退',
        icon: assetUrl('assets/kenney/skills/rubber_punch.png'),
        kind: 'attack',
        range: 6.0,
        swingMs: 340,
        cooldownMs: 600,
        knockback: 8.0,
        damage: 3,
        particleColor: 'yellow',
        particleCount: 22,
        weaponType: 'cast',
      },
      {
        id: 'space_shatter',
        name: '空間粉碎',
        desc: '粉碎空間製造毀滅衝擊，範圍5.0，攻擊力×5，CD 0.8秒。超強擊退終極技',
        icon: assetUrl('assets/kenney/skills/rubber_punch.png'),
        kind: 'attack',
        range: 5.0,
        swingMs: 400,
        cooldownMs: 800,
        knockback: 14.0,
        damage: 5,
        particleColor: 'white',
        particleCount: 28,
        weaponType: 'clap',
      },
    ],
  },
  {
    id: 'magma',
    name: '岩漿果實',
    desc: '化身滾燙岩漿，燃燒一切',
    color: '#cc3300',
    animStyle: 'magma',
    skills: [
      {
        id: 'magma_fist',
        name: '大噴火',
        desc: '揮出滾燙岩漿之拳，範圍5.0，攻擊力×3，CD 0.45秒。中距灼燒打擊',
        icon: assetUrl('assets/kenney/skills/rubber_punch.png'),
        kind: 'attack',
        range: 5.0,
        swingMs: 300,
        cooldownMs: 450,
        knockback: 7.0,
        damage: 3,
        particleColor: 'red',
        particleCount: 18,
        weaponType: 'punch',
      },
      {
        id: 'meteor_volcano',
        name: '流星火山',
        desc: '噴射岩漿流星群，範圍7.0，攻擊力×5，CD 0.85秒。遠距範圍高傷害',
        icon: assetUrl('assets/kenney/skills/rubber_punch.png'),
        kind: 'attack',
        range: 7.0,
        swingMs: 420,
        cooldownMs: 850,
        knockback: 6.0,
        damage: 5,
        particleColor: 'orange',
        particleCount: 30,
        weaponType: 'clap',
      },
      {
        id: 'magma_hound',
        name: '犬噛紅蓮',
        desc: '釋放岩漿犬追擊敵人，範圍4.5，攻擊力×2，CD 0.4秒。中距擊退追蹤',
        icon: assetUrl('assets/kenney/skills/rubber_punch.png'),
        kind: 'attack',
        range: 4.5,
        swingMs: 260,
        cooldownMs: 400,
        knockback: 8.5,
        damage: 2,
        particleColor: 'red',
        particleCount: 16,
        weaponType: 'cast',
      },
    ],
  },
  {
    id: 'sand',
    name: '沙沙果實',
    desc: '化身為沙，侵蝕與風暴並用',
    color: '#d4a843',
    animStyle: 'sand',
    skills: [
      {
        id: 'desert_sword',
        name: '砂漠寶刀',
        desc: '以沙之劍刃斬擊敵人，範圍5.5，攻擊力×2，CD 0.35秒。遠距劍系快速斬',
        icon: assetUrl('assets/kenney/items/sword_diamond.png'),
        kind: 'attack',
        range: 5.5,
        swingMs: 240,
        cooldownMs: 350,
        knockback: 5.5,
        damage: 2,
        particleColor: 'yellow',
        particleCount: 14,
        weaponType: 'sword',
      },
      {
        id: 'sand_trap',
        name: '流砂',
        desc: '製造流沙陷阱困住敵人，範圍4.0，攻擊力×3，CD 0.5秒。減速控制效果',
        icon: assetUrl('assets/kenney/skills/rubber_punch.png'),
        kind: 'attack',
        range: 4.0,
        swingMs: 300,
        cooldownMs: 500,
        knockback: 2.0,
        damage: 3,
        particleColor: 'yellow',
        particleCount: 20,
        weaponType: 'cast',
      },
      {
        id: 'sandstorm',
        name: '砂嵐',
        desc: '召喚沙暴席捲敵人，範圍6.0，攻擊力×4，CD 0.7秒。遠距範圍擊退',
        icon: assetUrl('assets/kenney/skills/rubber_punch.png'),
        kind: 'attack',
        range: 6.0,
        swingMs: 380,
        cooldownMs: 700,
        knockback: 7.0,
        damage: 4,
        particleColor: 'orange',
        particleCount: 26,
        weaponType: 'clap',
      },
    ],
  },
  {
    id: 'bomb',
    name: '爆爆果實',
    desc: '將一切化為爆炸，破壞力驚人',
    color: '#ff4444',
    animStyle: 'bomb',
    skills: [
      {
        id: 'bomb_punch',
        name: '爆拳',
        desc: '拳頭附帶爆炸衝擊，範圍3.5，攻擊力×2，CD 0.32秒。近距爆破擊退',
        icon: assetUrl('assets/kenney/skills/rubber_punch.png'),
        kind: 'attack',
        range: 3.5,
        swingMs: 220,
        cooldownMs: 320,
        knockback: 8.0,
        damage: 2,
        particleColor: 'orange',
        particleCount: 18,
        weaponType: 'slam',
      },
      {
        id: 'land_mine',
        name: '地雷',
        desc: '設置爆炸地雷引爆，範圍3.0，攻擊力×3，CD 0.45秒。近距強力擊退',
        icon: assetUrl('assets/kenney/skills/rubber_punch.png'),
        kind: 'attack',
        range: 3.0,
        swingMs: 260,
        cooldownMs: 450,
        knockback: 10.0,
        damage: 3,
        particleColor: 'red',
        particleCount: 22,
        weaponType: 'cast',
      },
      {
        id: 'big_explosion',
        name: '大爆炸',
        desc: '引發毀滅性大爆炸，範圍5.0，攻擊力×6，CD 0.9秒。超高傷害範圍擊退',
        icon: assetUrl('assets/kenney/skills/rubber_punch.png'),
        kind: 'attack',
        range: 5.0,
        swingMs: 400,
        cooldownMs: 900,
        knockback: 14.0,
        damage: 6,
        particleColor: 'red',
        particleCount: 32,
        weaponType: 'clap',
      },
    ],
  },
];
